enemy_data = {
    "tutorial": {
        "spider": {
            "sprite_name": "spider",
            "display_name": "Unwelcome Spider",
            "max_health": 20,
            "health": 20,
            "attack": 10,
            "defense": 20,
            "speed": 20,
        },
        "rat": {
            "sprite_name": "rat",
            "display_name": "Common Rat",
            "max_health": 25,
            "health": 25,
            "attack": 15,
            "defense": 25,
            "speed": 20,
        },
    },
    "ember_mountain": {
        "phoenix": {"sprite_name": "phoenix", "display_name": "Re-Alived Firebird"},
        "devil": {"sprite_name": "devil", "devil_name": "Devil-ling"},
    },
    "lushgrove": {
        "flower": {
            "sprite_name": "flower",
            "display_name": "Maneating Flower",
            "max_health": 25,
            "attack": 25,
            "health": 25,
            "defense": 15,
            "speed": 25,
        },
        "gryphon": {
            "sprite_name": "gryphon",
            "display_name": "Territorial Gryphon",
            "max_health": 35,
            "attack": 35,
            "health": 35,
            "defense": 35,
            "speed": 60,
        },
        "gorilla": {
            "sprite_name": "gorilla",
            "display_name": "Shredded Gorilla",
            "max_health": 40,
            "attack": 40,
            "health": 40,
            "defense": 40,
            "speed": 45,
        },
        "deer": {
            "sprite_name": "deer",
            "display_name": "Hormonal Deer",
            "max_health": 30,
            "attack": 25,
            "health": 30,
            "defense": 25,
            "speed": 75,
        },
    },
    "cinderdune": {
        "scorpion": {"sprite_name": "scorpion", "display_name": "Venemous Scorpion"},
        "skeleton": {"sprite_name": "skeleton", "display_name": "Dehydrated Dead"},
    },
    "riverfall": {
        "beaver": {"sprite_name": "beaver", "display_name": "Rabid Beaver"},
        "squid": {"sprite_name": "squid", "display_name": "Merciless Squid"},
    },
}
