player_data = {
    "name": "Skreet",
    "weapon_class": "magician",
    "color": "magenta",
    "companion_type": "cat",
    "companion_name": "Scoot",
    "completed_stories": ["intro_story"],
    "item_inventory": ["potion", "potion", "potion"],
    "item_inventory_capacity": 10,
    "battles_completed": 0,
    "current_funds": 100,
    "diamond_shards_obtained": 0,
    "player_max_health": 100,
    "player_current_health": 100,
    "player_max_attack": 100,
    "player_max_defense": 100,
    "player_max_speed": 100,
    "companion_max_health": 50,
    "companion_max_attack": 100,
    "companion_max_defense": 100,
    "companion_max_speed": 100,
    "companion_current_health": 20,
    "companion_current_attack": 20,
    "companion_current_defense": 20,
    "companion_current_speed": 20,
    "is_companion_alive": True,
    "current_weapon": {"name": "Lushgrove Tree Branch", "base_damage": 10},
    "current_attack": 50,
    "current_defense": 20,
    "current_speed": 35,
    "current_realm": "tutorial",
}
