player_data = {
    "name": "Slurmp",
    "weapon_class": "swordsman",
    "color": "green",
    "companion_type": "bear",
    "companion_name": "BURR",
    "completed_stories": ["intro_story"],
    "item_inventory": ["potion", "potion", "throwing knife"],
    "item_inventory_capacity": 10,
    "battles_completed": 0,
    "current_funds": 100,
    "diamond_shards_obtained": 0,
    "player_max_health": 100,
    "player_current_health": 100,
    "player_max_attack": 500,
    "player_max_defense": 500,
    "player_max_speed": 500,
    "companion_max_health": 50,
    "companion_max_attack": 300,
    "companion_max_defense": 300,
    "companion_max_speed": 300,
    "companion_current_health": 50,
    "companion_current_attack": 50,
    "companion_current_defense": 50,
    "companion_current_speed": 50,
    "is_companion_alive": True,
    "current_weapon": {"name": "Inherited Blunt Sword", "attack_boost": 1},
    "current_attack": 100,
    "current_defense": 150,
    "current_speed": 50,
    "current_realm": "lushgrove",
}
